version: '3.7'

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.6.0
    container_name: wazuh.manager
    restart: always
    ports:
      - "1514:1514/udp"    # Agent communication
      - "1515:1515"        # Registration service
    volumes:
      - wazuh_data:/var/ossec/data
    networks:
      - wazuh-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=wazuh-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - wazuh-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - wazuh-net

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.6.0
    container_name: wazuh.dashboard
    restart: always
    ports:
      - "443:5601"   # HTTPS access
    environment:
      - DASHBOARD_PASSWORD=wazuhadmin
      - DASHBOARD_USERNAME=wazuh
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    depends_on:
      - wazuh.manager
      - elasticsearch
    networks:
      - wazuh-net

volumes:
  es_data:
  wazuh_data:

networks:
  wazuh-net:
    driver: bridge
